# Get the Banking77 dataset

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("../data/train.csv")

In [44]:
df.shape

(10003, 2)

In [45]:
df.head()

                                                text      category
0                     I am still waiting on my card?  card_arrival
1  What can I do if my card still hasn't arrived ...  card_arrival
2  I have been waiting over a week. Is the card s...  card_arrival
3  Can I track my card while it is in the process...  card_arrival
4  How do I know if I will get my card, or if it ...  card_arrival

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10003 entries, 0 to 10002
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      10003 non-null  object
 1   category  10003 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [47]:
df.isnull().sum()

text        0
category    0
dtype: int64

In [48]:
df.describe()

                                  text                  category
count                            10003                     10003
unique                           10003                        77
top     I am still waiting on my card?  card_payment_fee_charged
freq                                 1                       187

In [49]:
df['category'].value_counts()

category
card_payment_fee_charged                            187
direct_debit_payment_not_recognised                 182
balance_not_updated_after_cheque_or_cash_deposit    181
wrong_amount_of_cash_received                       180
cash_withdrawal_charge                              177
                                                   ...
lost_or_stolen_card                                  82
card_swallowed                                       61
card_acceptance                                      59
virtual_card_not_working                             41
contactless_not_working                              35
Name: count, Length: 77, dtype: int64

In [50]:
df['category'].nunique()

77

In [51]:
df['text'] = df['text'].str.lower() # lowercase

In [52]:
df['text']= df['text'].str.strip()

In [53]:
df.sample(5) # random

,text,category
9050,i wanted to know what discounts were offered f...,exchange_charge
7247,why did you charge me a fee when i made a tran...,transfer_fee_charged
1104,when can i expect to receive my card?,card_delivery_estimate
7661,can you please explain the topping up transfer...,transfer_into_account
7181,why is my transfer more expensive than i thought?,transfer_fee_charged

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
vectorizer = TfidfVectorizer()

In [56]:
X = vectorizer.fit_transform(df['text'])

In [57]:
X.shape

(10003, 2320)

In [58]:
y = df['category']

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
model = LogisticRegression(max_iter=1000)

In [62]:
model.fit(X, y)

LogisticRegression(max_iter=1000)

In [63]:
# training dataset prediction

In [64]:
model.predict(X)

array(['card_arrival', 'card_arrival', 'card_arrival', ...,
       'country_support', 'country_support', 'country_support'],
      dtype=object)

In [65]:
from sklearn.metrics import accuracy_score, f1_score

In [66]:
accuracy_score(y, model.predict(X))

0.9309207237828652

In [67]:
f1_score(y, model.predict(X), average='macro')

0.9294262328529259

# test dataset

In [68]:
test_df = pd.read_csv('../data/test.csv')

In [69]:
test_df['text'] = test_df['text'].str.lower()

In [70]:
X_test = vectorizer.transform(test_df['text'])
y_test = test_df['category']

In [71]:
model.predict(X_test)

array(['card_linking', 'card_arrival', 'card_arrival', ...,
       'country_support', 'country_support', 'country_support'],
      dtype=object)

In [74]:
accuracy_score(y_test, model.predict(X_test))

0.8769480519480519

In [73]:
f1_score(y_test, model.predict(X_test), average='macro')

0.8768846181655345

In [75]:
import joblib

joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']